@startuml

title Cola Vending Machine 5 GUI Edition

package "User Interface Layer" {
    [Display]
    [Debug Display]
    [Mouse]
}

package "System Control Layer" {
    [Windowprocedure] #Cyan
}

package "Subsystems Layer" {
    [Coin handler]
    [Debitcard reader]
    [Drink dispenser]
    [Change dispenser]
    [Drink selections buttons]
}

package "Hardware Abstraction Layer" {
    [Hardware IO]
}

[Windowprocedure] -up-> [Mouse]
[Windowprocedure] -up-> [Display]
[Windowprocedure] -up-> [Debug Display]

[Windowprocedure] -down-> [Coin handler]
[Windowprocedure] -down-> [Debitcard reader]
[Windowprocedure] -down-> [Drink dispenser]
[Windowprocedure] -down-> [Change dispenser]
[Windowprocedure] -down-> [Drink selections buttons]

[Coin handler] -down-> [Hardware IO]
[Debitcard reader] -down-> [Hardware IO]
[Drink dispenser] -down-> [Hardware IO]
[Change dispenser] -down-> [Hardware IO]
[Drink selections buttons] -down-> [Hardware IO]

@enduml
