@startuml

title Cola Vending Machine 5 GUI Edition

package "User Interface Layer" {
    [Display]
    [Mouse]
}

package "System Control Layer" {
    [Windowprocedure] #Cyan
}

package "Subsystems Layer" {
    [Coin handeling]
    [Debitcard functionality]
    [Drink selection]
    [Screenbuffer]
    [Write to displaybuffers]
    [Append to displaybuffers]
}

package "Hardware Abstraction Layer" {
    [Hardware IO]
}

[Windowprocedure] -up-> [Mouse]
[Windowprocedure] -up-> [Display]

[Windowprocedure] -down-> [Coin handeling]
[Windowprocedure] -down-> [Debitcard functionality]
[Windowprocedure] -down-> [Drink selection]
[Windowprocedure] -down-> [Screenbuffer]
[Windowprocedure] -down-> [Write to displaybuffers]
[Windowprocedure] -down-> [Append to displaybuffers]

[Coin handeling] -down-> [Hardware IO]
[Debitcard functionality] -down-> [Hardware IO]
[Drink selection] -down-> [Hardware IO]
[Screenbuffer] -down-> [Hardware IO]
[Write to displaybuffers] -down-> [Hardware IO]
[Append to displaybuffers] -down-> [Hardware IO]

@enduml
