@startuml

title Windowprocedure Cola Vending Machine 5 GUI Edition

[*] --> Initialised : Wm_CREATE, WM_PAINT, WM_CTLCOLORSTATIC / INIT_Button(), INIT_Static, INIT_Menu, INIT_Edit

Initialised : sim_t simulation
Initialised : ~*pSim = &simulation
Initialised : pSim->moneyInWallet = (rand() % 5000 + 500)
Initialised : pSim->moneyInAccount = (rand() % 100000)	
Initialised : pSim->changeInMachine = change				
Initialised : pSim->moneyInMachine = 0					
Initialised : pSim->isDebitCardEntered = 0					
Initialised : pSim->postionInCardCode = 0					
Initialised : pSim->hasPaid = 0                   
Initialised : pSim->debitCardCode[4] = {0, 0, 0, 0}        
Initialised : pSim->POINTOFCONCEPTPASSWORD[4] = {1, 3, 3, 7}         
Initialised --> Windowprocedure

Windowprocedure --> WM_COMMAND
Windowprocedure --> WM_DESTROY

WM_DESTROY --> [*]

WM_COMMAND --> CM_COIN_BUTTON_PRESSED : CHP_CheckCoins()
CM_COIN_BUTTON_PRESSED : pSim->moneyInMachine = appropriate value
CM_COIN_BUTTON_PRESSED : pSim->moneyInMachine = appropriate value

WM_COMMAND --> CM_DRINK_BUTTON_PRESSED : CHP_CheckIfEnough()
CM_DRINK_BUTTON_PRESSED --> UserDrinkSelection : If you could pay it / WTSB_Redraw()
UserDrinkSelection --> Dispense_Drink : Deposites left over money in change buffer
Dispense_Drink --> Windowprocedure : WTDB_Debug()/ WTDB_Display()

CM_DRINK_BUTTON_PRESSED --> Windowprocedure : If you couldn't pay it 

WM_COMMAND --> CM_CHANGE_BUTTON_PRESSED : CHP_ChangeHandeling
CM_CHANGE_BUTTON_PRESSED --> Windowprocedure : WTDB_Debug()/ WTDB_Display()

WM_COMMAND --> CM_DEBITCARD_BUTTON_PRESSED : PWDC_DebitcardHandeling()
CM_DEBITCARD_BUTTON_PRESSED --> Enter_debitcard : First time enters card
CM_DEBITCARD_BUTTON_PRESSED --> Enter_debitcard : Second time takes card
Enter_debitcard --> Windowprocedure : WTDB_Debug()/ WTDB_Display()

WM_COMMAND --> CM_PIN_BUTTON_PRESSED : PWDC_AddPincodeBuffer()
CM_PIN_BUTTON_PRESSED --> Store_In_Buffer
Store_In_Buffer --> Windowprocedure : WTDB_Debug()/ WTDB_Display()

WM_COMMAND --> CM_PIN_BUTTON_PRESSED_OK : PWDC_RemovePincodeBuffer()
CM_PIN_BUTTON_PRESSED_OK --> Store_In_Buffer : Check storebuffer against database or in this case pSim->POINTOFCONCEPTPASSWORD
Store_In_Buffer --> Windowprocedure : WTDB_Debug()/ WTDB_Display()

WM_COMMAND --> CM_PIN_BUTTON_PRESSED_DEL : PWDC_CheckPincode()
CM_PIN_BUTTON_PRESSED_OK --> Store_In_Buffer : Remove one digit form store buffer
Store_In_Buffer --> Windowprocedure : WTDB_Debug()/ WTDB_Display()

WM_COMMAND --> CM_MENU_ITEM_ADMIN : Grant admin right and gain debug money
CM_MENU_ITEM_ADMIN --> WM_COMMAND : WTDB_Debug()/ WTDB_Display()

WM_COMMAND --> CM_MENU_ITEM_AUTHOR : Displaying system infomation
CM_MENU_ITEM_ADMIN --> WM_COMMAND : WTDB_Debug()/ WTDB_Display()

note right of Initialised #lime
    initializing sim_t a struct that contents much of the system infomation,
    and wil be accessed using pSim.
end note

note top of WM_COMMAND #lime
    Because windows api use a lot of WM_COMMAND
    I have simplified it to the base Commands.
end note

@enduml
